name: ai_vehicle_counter
description: UI/UX with mock API for AI Vehicle Counter
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.2.1
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.7.2

flutter:
  generate: true
  uses-material-design: true


